{% set name = "fastkml" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastkml-{{ version }}.tar.gz
  sha256: e21194b2a29f07a21045da6d7590f4968e1b82f63e0913510c728ab1a18233ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pygeoif <1.0
    - python >=3.6
    - python-dateutil

test:
  imports:
    - fastkml
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/cleder/fastkml"
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  summary: "Fast KML processing in python"
  doc_url: "https://pypi.org/project/fastkml/"

extra:
  recipe-maintainers:
    - mxr-conda
