{% set name = "fastkml" %}
{% set version = "1.1.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastkml-{{ version }}.tar.gz
  sha256: a786a80733763c16f5505efd7160a526f43b093bde767c9b35e816459bc6074e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - arrow
    - pygeoif >=1.5
    - typing-extensions >4
    - python >={{ python_min }}

test:
  imports:
    - fastkml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: "https://github.com/cleder/fastkml"
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  summary: "Fast KML processing in python"
  doc_url: "https://pypi.org/project/fastkml/"

extra:
  recipe-maintainers:
    - mxr-conda
    - ReimarBauer
